# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Yolo-zzy的博客
subtitle: 
description: 'Yolo-zzy的博客'
keywords: 'Yolo-zzy'
author: yolo
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
# url: https://yolo-zzy.github.io/
url:  https://www.yolozzy.online/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 8
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-butterfly-dev

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy: 
- type: git
  repo: git@129.211.27.198:/home/git/blog.git
  branch: master
 # github: git@github.com:yolo-zzy/yolo-zzy.github.io.git
- type: git
  repo: git@github.com:yolo-zzy/yolo-zzy.github.io.git
  branch: master



#本地搜索系统
search:
  path: search.xml
  field: post
  content: true

# hexo-butterfly-categories-card
# see https://akilar.top/posts/a9131002/
categoryBar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: / # 应用页面
  layout: # 挂载容器类型
    type: class
    name: recent-posts
    index: 0
  column: odd # odd：3列 | even：4列
  row: 1 #显示行数，默认两行，超过行数切换为滚动显示
  message:
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/raidenshogun.jpg
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/shenhe.jpg
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/shenlilinghua2.jpg
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/ningguang.png
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/ganyu.jpg
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/6legs.jpg
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/jingliu.jpg
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/rosaria.jpg
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/acheron.png
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/robin.jpg
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/ruanmei.jpg
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/silverwolf.jpg
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/blade.jpg
    - descr: 
      cover: https://cdn.jsdelivr.net/gh/Yolo-ZZY/Image/castorice.jpg





  custom_css: https://npm.elemecdn.com/hexo-butterfly-categories-card@1.0.0/lib/categorybar.css

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true #开关插件版看板娘
  scriptFrom: local # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  # scriptFrom: jsdelivr # jsdelivr CDN
  # scriptFrom: unpkg # unpkg CDN
  # scriptFrom: https://npm.elemecdn.com/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-shizuku # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://npm.elemecdn.com/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  display:
    position: left #控制看板娘位置
    width: 150 #控制看板娘大小
    height: 300 #控制看板娘大小
  mobile:
    show: false
     # 手机中是否展示


# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: all # 应用页面
  timemode: date #date/updated
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper_css: /css/swiper.min.css #swiper css依赖
  swiper_js: /js/swiper.min.js #swiper js依赖
  custom_css: /css/swiperstyle.css # 适配主题样式补丁
  custom_js: /js/swiper_init.js # swiper初始化方法